//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratorHTML.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class formularioContacto
    {
        public int formularioId { get; set; }
        public string Nombre { get; set; }
        public string apellido { get; set; }
        public string Email { get; set; }
        public string telefono { get; set; }
        public string facebook { get; set; }
        public string instagram { get; set; }
        public string whatsApp { get; set; }
    }
}
