//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratorHTML.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfPersonal
    {
        public int infPersonalId { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string NombreCompletoPadre { get; set; }
        public string imgPadre { get; set; }
        public string NombreCompletoMadre { get; set; }
        public string imgMadre { get; set; }
        public string NombrecompletoPadreAbuela { get; set; }
        public string imgPadreAbuela { get; set; }
        public string NombreCompletoPadreAbuelo { get; set; }
        public string imgPadreAbuelo { get; set; }
        public string NombrecompletoMadreAbuela { get; set; }
        public string imgMadreAbuela { get; set; }
        public string NombreCompletoMadreAbuelo { get; set; }
        public string imgMadreAbuelo { get; set; }
        public string NombreCompletoAbuelaBisabuela { get; set; }
        public string imgAbuelaBisabuela { get; set; }
        public string NombreCompletoAbuelaBisabuelo { get; set; }
        public string imgAbuelaBisabuelo { get; set; }
        public string NombreCompletoAbueloBisabuela { get; set; }
        public string imgAbueloBisabuela { get; set; }
        public string NombreCompletoAbueloBisabuelo { get; set; }
        public string imgAbueloBisabuelo { get; set; }
    }
}
