//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratorHTML.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PraticaHTMLEntities3 : DbContext
    {
        public PraticaHTMLEntities3()
            : base("name=PraticaHTMLEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<formularioContacto> formularioContactos { get; set; }
        public virtual DbSet<InfPersonal> InfPersonals { get; set; }
        public virtual DbSet<pasatiempos> pasatiempos { get; set; }
        public virtual DbSet<SeriesFav> SeriesFavs { get; set; }
        public virtual DbSet<youtuberFav> youtuberFavs { get; set; }
    }
}
