//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratorHTML.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeriesFav
    {
        public int serieId { get; set; }
        public string SerieFav { get; set; }
        public string trailer { get; set; }
    }
}
